import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Work",
  description: "Generated by create next app",
};

const Work = () => {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      Work
    </main>
  )
}

export default Work